//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MFCApplication2.rc 使用
//
#define IDOK2                           2
#define IDOK3                           3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_SETTINGS                    100
#define IDS_ABOUTBOX                    101
#define IDD_MFCAPPLICATION2_DIALOG      102
#define ID_CPU                          102
#define IDD_FORMVIEW                    103
#define ID_RAM                          103
#define IDD_XT                          104
#define ID_JINGCHENG                    104
#define IDD_ZIZHI                       105
#define IDD_XUAN                        106
#define IDD_SHUTDOWN                    107
#define IDD_BINGDU                      108
#define IDD_HOME                        109
#define IDR_MENU1                       130
#define IDD_MYMOUDLEDIALOG              131
#define IDD_MYTHREAD_DIALOG             133
#define IDD_FILEINFO_DIALOG             137
#define IDR_MENU2                       141
#define IDI_ICON1                       145
#define IDR_MAINFRAME                   145
#define IDD_SERVICE_DIALOG              156
#define IDR_MENU3                       158
#define IDD_UNINSTALL_DIALOG            159
#define IDR_MENU4                       161
#define IDI_ICON2                       166
#define IDD_STARTUP_DIALOG              166
#define IDD_CLEARUP_DIALOG              176
#define IDD_TASK_DIALOG                 177
#define IDR_MENU8                       188
#define IDC_LIST_MODULE                 1001
#define IDC_LIST_THREAD                 1003
#define IDC_BUTTON1                     1005
#define IDC_END                         1006
#define IDC_EXIT                        1007
#define IDC_BUTTON2                     1008
#define IDC_ABOUT                       1008
#define IDC_ZIZHI_TOOLS                 1009
#define IDC_BUTTON3                     1009
#define IDC_XT_TOOLS                    1010
#define IDC_BUTTON4                     1010
#define IDC_HOME                        1011
#define IDC_BUTTON5                     1011
#define IDC_BOTTON                      1012
#define IDC_BUTTON6                     1012
#define IDC_BOTTON2                     1013
#define IDC_EDIT                        1013
#define IDC_BOTTON3                     1014
#define IDC_EDIT1                       1014
#define IDC_BOTTON4                     1015
#define IDC_EDIT2                       1015
#define IDC_BOTTON5                     1016
#define IDC_BOTTON6                     1017
#define IDC_COMBO1                      1017
#define IDC_BOTTON7                     1018
#define IDC_MFCLINK1                    1018
#define IDC_MFCLINK                     1018
#define IDC_LIST_FILE                   1018
#define IDC_COMBO2                      1018
#define IDC_BOTTON8                     1019
#define IDC_COMBO3                      1019
#define IDC_BOTTON9                     1020
#define IDC_COMBO                       1020
#define IDC_BOTTON10                    1021
#define IDC_TAB1                        1021
#define IDC_BOTTON11                    1022
#define IDC_BOTTON12                    1023
#define IDC_BOTTON13                    1024
#define IDC_BOTTON14                    1025
#define IDC_EXPLORER1                   1025
#define IDC_BUTTON7                     1026
#define IDC_BOTTON15                    1026
#define IDC_BUTTON9                     1027
#define IDC_LIST_UNISTALL               1027
#define IDC_BUTTON8                     1027
#define IDC_BOTTON16                    1027
#define IDC_LIST_STARTUP                1028
#define IDC_BUTTON11                    1028
#define IDC_BOTTON17                    1028
#define IDC_STATIC_PATH                 1029
#define IDC_BOTTON18                    1029
#define IDC_CHECK1                      1030
#define IDC_BOTTON19                    1030
#define IDC_CHECK3                      1031
#define IDC_STATIC1                     1031
#define IDC_CHECK4                      1032
#define IDC_BUTTON10                    1032
#define IDC_CHECK5                      1033
#define IDC_STATIC3                     1033
#define IDC_CHECK6                      1034
#define IDC_STATIC4                     1034
#define IDC_CHECK7                      1035
#define IDC_STATIC5                     1035
#define IDC_BUTTON12                    1035
#define IDC_CHECK8                      1036
#define IDC_STATIC2                     1036
#define ID_CANCEL                       1036
#define IDC_STATIC7                     1037
#define IDC_CHECK9                      1037
#define IDC_START                       1037
#define IDC_STATIC6                     1037
#define IDC_STATIC8                     1038
#define IDC_CHECK2                      1038
#define IDC_LIST_TASK                   1038
#define IDC_STATIC9                     1039
#define IDC_STATIC10                    1040
#define IDC_STATIC11                    1041
#define ID_BUTTON2                      32771
#define ID_ENDPROCESS                   32787
#define ID_ENUMMOUDLE                   32788
#define ID_OPENFILE                     32789
#define ID_SUSPENPROCESS                32790
#define ID_RESUMEPROCESS                32791
#define ID_ENUMTHREAD                   32792
#define ID_RESUMETHREAD                 32797
#define ID_SUSPENDTHREAD                32798
#define ID_TERMINATETHREAD              32800
#define ID_TOP                          32801
#define ID_GUANGJI                      32805
#define ID_CHONGQI                      32806
#define ID_ZHUXIAO                      32807
#define ID_FILEINFO                     32808
#define ID_END                          32809
#define ID_NEWTASK                      32810
#define ID_STARTSERVICE                 32816
#define ID_REFERSHSERVICE               32817
#define ID_STOPSERVICE                  32818
#define ID_UNINSTALL                    32822
#define ID_SINGLEFILEINFO               32836
#define ID_DELETESTATTUP                32845
#define ID_REFERSHSTATRUP               32846
#define ID_REFERSHSOFTLIST              32848
#define ID_LOCK                         32850

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
